
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INTEGER PRIMARY KEY,
EMPLOYEE_FIRSTNAME VARCHAR2(100),
EMPLOYEE_LASTNAME VARCHAR2(100),
DEPARTMENT_ID INTEGER NOT NULL,
SALARY NUMBER(6,2),
EMP_EMAIL VARCHAR2(100)
);
/
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(100)
);
/
-- CREATE A SEQUENCE AND TRIGGER TO AUTOGENERATE PPRIMARY KEYS FOR BOTH TABLES
CREATE SEQUENCE SEQUENCE_1
START WITH 100
INCREMENT BY 1
/
CREATE OR REPLACE TRIGGER TR 
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
	SELECT SEQUENCE_1.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(1, 'SHYAM', 'VASANJEE',72, 2500,'SHYAM@GMAIL.COM');
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(2, 'LEONARD', 'EULER',34, 2500,'OILER_NOT_U_LER@GMAIL.COM');
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(3, 'ALBERT', 'EINSTIEN',14, 2500,'GENERALRELATIONS@GMAIL.COM');
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(4, 'EMMY', 'NOETHERS',25, 2500,'SYMMETRYBOSS1212@GMAIL.COM');
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(5, 'JOAN', 'DOE',19, 2500,'WHOAMI@GMAIL.COM');
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_FIRSTNAME,EMPLOYEE_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES(6, 'MICHAEL', 'LEBOWSKI',25, 2500,'THEDUDEABIDES@GMAIL.COM');
/